#!/usr/bin/env bash
# redirection script

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
echo 'Holberton School' | sudo tee /var/www/html/index.html > /dev/null
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
