#!/usr/bin/env bash
# setup haproxy
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend http
        bind *:80
        mode http
        default_backend semil-backend
backend semil-backend
	balance roundrobin
	server 208196-web-01 web-01.semiloreom.tech/:80 check
	server 208196-web-02 web-02.semiloreom.tech/:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
