#!/usr/bin/env bash
# configure haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  semil-frontend
        bind *:80
        mode http
        default_backend semil-backend
backend semil-backend
        balance roundrobin
        server 208196-web-01 100.24.74.22:80 check
        server 208196-web-02 3.80.19.54:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
